# Fly.io配置文件
app = "memory-app"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile.fly"

[env]
  PORT = "8080"
  PYTHONPATH = "."

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/api/v1/health"
  protocol = "http"
  tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "python migrations/migrations_001.py"

[[statics]]
  guest_path = "/app/dist"
  url_prefix = "/"
  headers = { "Cache-Control" = "public, max-age=31536000" }