
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('app', 'app'),
        ('data', 'data'),
        ('migrations', 'migrations'),
        ('uvicorn_loggin_config.json', '.'),
        ('Memory_api.py', '.'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.middleware.trustedhost',
        'fastapi.middleware.gzip',
        'fastapi.responses',
        'fastapi.staticfiles',
        'starlette',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.middleware.sessions',
        'starlette.responses',
        'starlette.staticfiles',
        'tortoise',
        'tortoise.backends.sqlite',
        'tortoise.backends.mysql',
        'tortoise.backends.asyncpg',
        'tortoise.models',
        'tortoise.fields',
        'tortoise.contrib.pydantic',
        'aiosqlite',
        'aiomysql',
        'asyncpg',
        'passlib.handlers.argon2',
        'passlib.handlers.bcrypt',
        'passlib.context',
        'argon2',
        'pydantic',
        'pydantic.fields',
        'pydantic.validators',
        'pydantic_settings',
        'email_validator',
        'multipart',
        'python_multipart',
        'PIL',
        'PIL.Image',
        'PIL._tkinter_finder',
        'boto3',
        'botocore',
        'requests',
        'aiohttp',
        'loguru',
        'jwt',
        'pkg_resources.py2_warn',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='memory-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
