[build]
  base = "web"
  publish = "../dist"
  command = "npm install && npm run build && cd .. && pip install -r netlify-requirements.txt"

[build.environment]
  NODE_VERSION = "last"
  PYTHON_VERSION = "3.11"
  PIP_CACHE_DIR = "/opt/buildhome/.cache/pip"
  # 避免 Rust 编译，使用预编译包
  PIP_NO_BUILD_ISOLATION = "false"
  PIP_PREFER_BINARY = "1"
  # 设置环境变量
  PYTHONPATH = "/opt/buildhome/repo"
  DATABASE_URL = "sqlite:///./data/db.sqlite3"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  python_runtime = "3.11"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"