name: Build Multi-Platform Desktop App

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: read
  checks: write
  deployments: write
  issues: write
  discussions: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
        include:
          - platform: macos-latest
            os: macos
            arch: universal
            ext: dmg
          - platform: windows-latest
            os: windows
            arch: x64
            ext: msi
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || matrix.platform == 'ubuntu-20.04' && 'x86_64-unknown-linux-gnu' || 'x86_64-pc-windows-msvc' }}
          
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './web/src-tauri -> target'
          
      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          
      - name: Install frontend dependencies
        working-directory: ./web
        run: npm ci
        
      - name: Install Python dependencies
        run: pip install -r requirements.txt
        
      - name: Prepare Python distribution for packaging
        run: |
          python3 prepare_python_dist.py
        env:
          PYTHONPATH: ${{ github.workspace }}
          
      - name: Test backend server (optional) - Unix
        if: matrix.platform != 'windows-latest'
        run: |
          python3 run.py &
          BACKEND_PID=$!
          sleep 5
          kill $BACKEND_PID || true
        env:
          PYTHONPATH: ${{ github.workspace }}
          
      - name: Test backend server (optional) - Windows
        if: matrix.platform == 'windows-latest'
        run: |
          $process = Start-Process -FilePath "python" -ArgumentList "run.py" -PassThru -NoNewWindow
          Start-Sleep -Seconds 5
          Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
        shell: powershell
        env:
          PYTHONPATH: ${{ github.workspace }}
        
      - name: Build Tauri app (macOS Universal)
        if: matrix.platform == 'macos-latest'
        working-directory: ./web
        run: |
          npm run tauri:build -- --target universal-apple-darwin || {
            echo "Universal build failed, trying x86_64 build..."
            npm run tauri:build -- --target x86_64-apple-darwin
          }
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          
      - name: Build Tauri app (Linux)
        if: matrix.platform == 'ubuntu-20.04'
        working-directory: ./web
        run: npm run tauri:build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          
      - name: Build Tauri app (Windows)
        if: matrix.platform == 'windows-latest'
        working-directory: ./web
        run: npm run tauri:build -- --bundles nsis
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          
      - name: Upload artifacts (macOS)
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: |
            web/src-tauri/target/*/release/bundle/dmg/*.dmg
          retention-days: 30
          

      - name: Upload artifacts (Windows)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: |
            web/src-tauri/target/release/bundle/nsis/*.exe
          retention-days: 30
          
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      packages: write
      actions: read
      checks: write
      deployments: write
      issues: write
      discussions: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release with GitHub CLI
        run: |
          # Create release
          gh release create ${{ github.ref_name }} \
            --repo ${{ github.repository }} \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes \
            --latest
          
          # Upload artifacts
          find artifacts -type f \( -name "*.dmg" -o -name "*.exe" -o -name "*.msi" \) -exec gh release upload ${{ github.ref_name }} --repo ${{ github.repository }} {} \;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}