name: Build Frontend Only

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install frontend dependencies
      working-directory: ./web
      run: npm ci

    - name: Build frontend
      working-directory: ./web
      run: npm run build

    - name: Upload frontend build artifacts
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: dist/
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      pull-requests: write
      issues: write
      repository-projects: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend-dist
          
      - name: Create frontend distribution archive
        run: |
          cd frontend-dist
          tar -czf ../frontend-dist.tar.gz .
          cd ..
          
      - name: Get release tag
        id: get_tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: frontend-dist.tar.gz
          name: "Frontend Release ${{ steps.get_tag.outputs.tag }}"
          body: "Automated frontend build release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}