/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
    AppPage: typeof import('./src/components/page/AppPage.vue')['default']
    AppProvider: typeof import('./src/components/common/AppProvider.vue')['default']
    CommonPage: typeof import('./src/components/page/CommonPage.vue')['default']
    CrudModal: typeof import('./src/components/table/CrudModal.vue')['default']
    CrudTable: typeof import('./src/components/table/CrudTable.vue')['default']
    CustomIcon: typeof import('./src/components/icon/CustomIcon.vue')['default']
    IconPicker: typeof import('./src/components/icon/IconPicker.vue')['default']
    LoadingEmptyWrapper: typeof import('./src/components/common/LoadingEmptyWrapper.vue')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTag: typeof import('naive-ui')['NTag']
    NUpload: typeof import('naive-ui')['NUpload']
    QueryBar: typeof import('./src/components/query-bar/QueryBar.vue')['default']
    QueryBarItem: typeof import('./src/components/query-bar/QueryBarItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollX: typeof import('./src/components/common/ScrollX.vue')['default']
    SvgIcon: typeof import('./src/components/icon/SvgIcon.vue')['default']
    TheIcon: typeof import('./src/components/icon/TheIcon.vue')['default']
  }
}
